name: pub_api
description: A package to use Pub's API.
homepage: https://github.com/Ampless/pub_api

version: 0.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pub_semver: ^2.0.0
  schttp: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
