name: pub_api
description: A package to use Pub's API.
version: 0.0.7
homepage: https://github.com/Ampless/pub_api

environment:
  sdk: ^3.0.0

dependencies:
  pub_semver: ^2.0.0
  schttp: ^5.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
