name: pub_api
description: A package to use Pub's API.
homepage: https://github.com/Ampless/pub_api

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  version: ^1.2.0
  schttp: ^0.2.8

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
